version: 2
updates:
- package-ecosystem: maven
  directory: "/"
  schedule:
    interval: daily
    time: "04:00"
  open-pull-requests-limit: 10
  ignore:
  # Ignore these until we move to Jakarta
  - dependency-name: 'org.apache.activemq:activemq-client'
    versions:
    - '>= 6'
  - dependency-name: 'org.apache.activemq:activemq-openwire-legacy'
    versions:
    - '>= 6'
  - dependency-name: 'org.apache.activemq:activemq-broker'
    versions:
    - '>= 6'
  - dependency-name: 'org.apache.activemq:activemq-kahadb-store'
    versions:
    - '>= 6'
  - dependency-name: 'org.apache.activemq:activemq-spring'
    versions:
    - '>= 6'
  - dependency-name: 'org.apache.activemq:activemq-amqp'
    versions:
    - '>= 6'
  # graalvm changed a lot in 24.x
  - dependency-name: 'org.graalvm.js:js'
    versions:
    - '>= 24'
  # this fails from that version
  - dependency-name: 'com.fasterxml.jackson.core:jackson-databind'
    versions:
    - '>= 2.22'
